server.port=8081

spring.datasource.url=jdbc:h2:mem:vulnapp;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# verbose errors leak stack traces to the client
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true

# session cookie without Secure/HttpOnly hardening
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=false

# VULN:VULN-35:CWE-1021:config no X-Frame-Options / CSP frame-ancestors -> clickjacking
